Expand and update documentation
inkytonik/cooma pull request #79
Opened 2022-06-07 04:58 UTC by nhweston

2022-07-03 07:22 UTC, inkytonik requested changes
This looks really good. Thanks for the effort. I left a few minor comments but otherwise it looks good to merge.

2022-07-03 07:22 UTC, inkytonik commented on doc/02_composite-types.md
> +> 1:1:error: record concatenation has overlapping field(s) b
I think the `x & y` went missing here.

2022-07-03 07:22 UTC, inkytonik commented on README.md
> +* Anthony Sloane (Anthony.Sloane@mq.edu.au)
Please change my email to `inkytonik@gmail.com` since eventually my MQ email will go away.

2022-07-03 07:22 UTC, inkytonik commented on doc/03_capabilities.md
> +While `Reader` as an command-line argument type directs the compiler to treat
`as a command-line argument`

2022-07-07 04:51 UTC, nhweston commented
Done.

2022-07-07 11:32 UTC, merged